### ISSUE TITLE
Updates, Firefox, Edge?

### ISSUE THREAD

**Issue by Lewiscowles1986** [RobSpectre/Trump-Filter#15]
It looks like you were so ahead of the times making this in 2011 😆 

Anyway, I've made some triple browser extensions before; we've got mutation filters now so even SPA's should be un trumpable.

Open to PR's?

**Comment by RobSpectre** [comment]
@Lewiscowles1986 Certainly up for it, but given the upstream bug is mitigated by Twitter and assigned to the next sprint for the United States Senate, do we feel this is necessary?

**Comment by Lewiscowles1986** [comment]
Good point 😉
